### ISSUE TITLE
可否增加JOOX音樂解鎖

### ISSUE THREAD

**Issue by ghost** [unlock-music/unlock-music#130]
- 请按照此模板填写，否则可能立即被关闭

**背景和说明**

简要说明产生此想法的背景和此想法的具体内容
```
在香港有一個APP叫做joox，註冊就送15天會員。

但是會員期間下載的歌曲只能在客戶端內部播放，不能導出，或者在其他音樂播放器上播放。

希望有一種解密算法可以使已付費用戶或者會員在過期後也能聽到歌曲
```

**实现途径**

- 如果没有设计方案，请简要描述实现思路
- 如果你没有任何的实现思路，请通过[Discussions](https://github.com/ix64/unlock-music/discussions)或者Telegram进行讨论

就該App的加密方式進行反向研究
然後編寫算法
實現解密JOOX

**附加信息**

給大家一點背景，JOOX是騰訊公司針對香港用戶開發的一款App

**Comment by David-H-1** [comment]
我稍後可以樣本文件傳送給您

**Comment by David-H-1** [comment]
樣本檔案鏈接係
https://cp.sync.com/dl/757ee9880#w78tujze-zfbe8gux-nuy6u958-xy98fxyu

**Comment by David-H-1** [comment]
注意需要目的是香港的VPN方可下載和體驗會員

**Comment by nigelmusic** [comment]
我也需要解密JOOX的ofl_en檔，謝謝

**Comment by jixunmoe** [comment]
Joox 的加密比较麻烦，需要 root 设备获取应用程序在首次启动时生成的一个 uuid。

---

root 后进入终端（使用终端模拟器键入 `su`、或在电脑使用 `adb shell su` 进入），粘贴或键入下述内容后回车：

```
grep -aoE "OPENUDID2[^0-9a-f]*([0-9a-f]{32})" /data/data/com.tencent.ibg.joox/files/mmkv/globalconfig | tail -c 32
```

会得到一个 32 位字符的设备 uuid。请不要公开该值，joox 会上报当前设备信息。

![image](https://user-images.githubusercontent.com/5713045/146625124-47bd63ec-9c23-494d-aca9-0adeed53cb73.png)

不推荐对 _你现在正在使用的主设备_ 进行 root，因为有一定概率产生各类不可预知的问题（如部分应用不兼容、失去厂家保修）。建议买一个二手安卓设备或已经淘汰的设备进行 root 操作。

---

下一步：等待解密代码放出…

解密的代码待我过几天整理一份简单的实现放出来。

如果你有兴趣逆向，你也可以自己折腾一番。

**Comment by jixunmoe** [comment]
开启了新的 pr，可以在 #215 追踪进度。

**Comment by ix64** [comment]
https://github.com/unlock-music/unlock-music/pull/215 已完成 JOOX 集成
