### ISSUE TITLE
ncm转换后的mp3文件无法在Walkman上显示封面信息

### ISSUE THREAD

**Issue by NneurotransmitterR** [unlock-music/unlock-music#142]
- [x] 我确认已经搜索过Issue不存在相同的Issue

**Bug描述**

转换后的.ncm文件在索尼NW-A55上无法显示封面

**复现方法**

下载.ncm文件(mp3,320k)转换后拷贝至Walkman

**程序截图或者Console报错信息**

![屏幕截图](https://user-images.githubusercontent.com/47296255/111465544-37a1f000-875d-11eb-85d1-b7faf0cb699f.jpg)
![1615982628227](https://user-images.githubusercontent.com/47296255/111466235-f9590080-875d-11eb-8317-1e23b87a91eb.jpg)

**环境信息:**

 - 操作系统和浏览器：Windows 10, Chrome 89
 - 程序版本：Build 2020/12/19, legacy
 - 获取音乐文件所使用的客户端及其版本信息：网易云音乐for PC, 2.7.6

**附加信息**

[使用这个工具转换的文件没有此问题。](https://github.com/FIFCOM/ncmdump)

**Comment by ix64** [comment]
有可能是ID3图像的Description不同所致（但按照ID3，此项的区别不应对图像识别产生任何影响）
不过抱歉，本人暂无相关设备，欢迎有设备者提交PR。

**Comment by hikali8** [comment]
本人有幸遇到过这种情况，一般而言这是由于mp3文件的cover图片格式不正确、cover description过长等问题，导致MP3播放设备无法正确显示封面。可以使用Mp3tag等可以编辑音频文件元数据的软件来修正此类错误。
下面提供Mp3tag修正此类问题的步骤。首先打开Mp3tag，打开文件后选中，右键封面，点击Adjust cover...，然后Format一栏选择JPEG，Max. Size填和原封面一样大或更大，点击OK，即可将封面转换为MP3播放设备可识别的JPEG图片格式格式；然后再右键封面，点击Set cover description...，把方框内的内容全部删除，点击OK；最后点击左上角的保存按钮，完毕。
经确认，修正后的MP3文件已可以在MP3播放设备上正常显示封面。

**Comment by ix64** [comment]
> 点击Set cover description...，把方框内的内容全部删除，点击OK

所以是设置 **空的Description** 吗？

**Comment by NneurotransmitterR** [comment]
是的，设置空的Cover Description后我的设备就能正常显示封面了。

**Comment by ix64** [comment]
https://28b8a0e3.unlock-music-2dd0.pages.dev/ 开了一个分支进行测试，欢迎使用和反馈
