### ISSUE TITLE
无法解锁的mgg样本

### ISSUE THREAD

**Issue by donwang-ux** [unlock-music/unlock-music#145]
* 请按照此模板填写，否则可能立即被关闭

- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [x] 我有证据表明这是程序导致的问题（如不确认，可以在[Discussions](https://github.com/ix64/unlock-music/discussions)内提出）

**Bug描述**

Mgg文件不能解锁，希望可以看看，谢谢！

**复现方法**

链接：https://pan.baidu.com/s/1lRaQnGSssvlEHCCLl7oJGQ 
提取码：2t0i 

**环境信息:**

 - 操作系统和浏览器：
 - 程序版本：
 - 获取音乐文件所使用的客户端及其版本信息：

**附加信息**

其他能够帮助确认问题的信息

**Comment by wfsg00098** [comment]
请使用其他客户端下载QQ音乐的歌曲，可以解锁。Windows版的mgg不是那么容易搞定的

**Comment by donwang-ux** [comment]
> 请使用其他客户端下载QQ音乐的歌曲，可以解锁。Windows版的mgg不是那么容易搞定的

非常感谢，Mac端下载的版本可以解锁。

**Comment by j19981106** [comment]
环境信息:

操作系统和浏览器：
Windows 10 专业版 20H2 19042.928 
Microsoft Edge 版本 90.0.818.41 (官方内部版本) (64 位)
程序版本：v1.8.1
获取音乐文件所使用的客户端及其版本信息：QQ音乐18.07.5313.0310

样本：
[周杰伦 - 不爱我就拉倒.mgg.zip](https://github.com/ix64/unlock-music/files/6350942/-.zip)
[周杰伦 - 等你下课 (with 杨瑞代).mgg.zip](https://github.com/ix64/unlock-music/files/6350944/-.with.zip)
[周杰伦 - 枫.mgg.zip](https://github.com/ix64/unlock-music/files/6350947/-.zip)
[周杰伦 - 花海.mgg.zip](https://github.com/ix64/unlock-music/files/6350950/-.zip)
[周杰伦 - 麦芽糖.mgg.zip](https://github.com/ix64/unlock-music/files/6350923/-.zip)
[周杰伦 - 青花瓷.mgg.zip](https://github.com/ix64/unlock-music/files/6350925/-.zip)
[韩红 _ 林俊杰 - 飞云之下.mgg.zip](https://github.com/ix64/unlock-music/files/6350899/_.-.zip)
[林俊杰 - 编号89757.mgg.zip](https://github.com/ix64/unlock-music/files/6350905/-.89757.zip)
[林俊杰 - 盗.mgg.zip](https://github.com/ix64/unlock-music/files/6350908/-.zip)
[林俊杰 - 简简单单.mgg.zip](https://github.com/ix64/unlock-music/files/6350911/-.zip)
[林俊杰 - 明天.mgg.zip](https://github.com/ix64/unlock-music/files/6350926/-.zip)
[林俊杰 - 木乃伊.mgg.zip](https://github.com/ix64/unlock-music/files/6350928/-.zip)
[林俊杰 - 莎士比亚的天份.mgg.zip](https://github.com/ix64/unlock-music/files/6350929/-.zip)
[林俊杰 - 十秒的冲动.mgg.zip](https://github.com/ix64/unlock-music/files/6350930/-.zip)
[林俊杰 - 听不懂 没关系.mgg.zip](https://github.com/ix64/unlock-music/files/6350931/-.zip)
[林俊杰 - 无尽的思念.mgg.zip](https://github.com/ix64/unlock-music/files/6350932/-.zip)
[林俊杰 - 心墙.mgg.zip](https://github.com/ix64/unlock-music/files/6350934/-.zip)
[林俊杰 - 一千年以后.mgg.zip](https://github.com/ix64/unlock-music/files/6350936/-.zip)
[林俊杰 - 一千年以前 (伴奏).mgg.zip](https://github.com/ix64/unlock-music/files/6350938/-.zip)
[林俊杰 _ 林俊峰 - 飞机.mgg.zip](https://github.com/ix64/unlock-music/files/6350939/_.-.zip)
[萧敬腾 _ 林俊杰 - Hello (录音室版).mgg.zip](https://github.com/ix64/unlock-music/files/6350941/_.-.Hello.zip)

**Comment by cyy-CHN** [comment]
周杰伦许多歌曲至今仍无法解锁
如：
周杰伦 - 明明就.mgg
周杰伦 - 发如雪.mgg
周杰伦 - 告白气球.mgg
周杰伦 - 双截棍.mgg
