### ISSUE TITLE
批量保存

### ISSUE THREAD

**Issue by westCastle** [unlock-music/unlock-music#146]
批量保存时，每次弹出需要选择保存位置。

希望可以优化为之前选择目录，全部自动保存在该目录中，或者一批中后续的自动保存在第一个选择的目录中。

场景：Windows10 + Google Chrome

**Comment by webliuxiang** [comment]
+1

**Comment by emmmx** [comment]
- Already supported on [v1.9.0-beta](https://github.com/unlock-music/unlock-music/releases/tag/v1.9.0-beta)
- Have a taste: https://unlock-music-2dd0.pages.dev/
