### ISSUE TITLE
FourCC contains invalid characters

### ISSUE THREAD

**Issue by Kyaru2333** [unlock-music/unlock-music#169]
* 请按照此模板填写，否则可能立即被关闭

-  我确认已经搜索过Issue不存并确认相同的Issue

**Bug描述**

Error: FourCC contains invalid characters: 75 dd 35 26 "uÝ5&"，HEST - Waiting For Love (Remix).mflac，参考使用提示

**复现方法**

[HEST - Waiting For Love (Remix).zip](https://github.com/unlock-music/unlock-music/files/6766645/HEST.-.Waiting.For.Love.Remix.zip)

**程序截图或者Console报错信息**

如果可以请提供二者之一
Error: FourCC contains invalid characters: 75 dd 35 26 "uÝ5&"，HEST - Waiting For Love (Remix).mflac，参考使用提示

**环境信息:**

 - 操作系统和浏览器：chrome 90
 - 程序版本：1.90-beta
 - 获取音乐文件所使用的客户端及其版本信息：1813

**附加信息**

其他能够帮助确认问题的信息

**Comment by GotTal** [comment]
相同问题+1

**Comment by lunjielee** [comment]
同样问题,
Error: FourCC contains invalid characters: 12 7e 11 09 "~ "，YOASOBI (ヨアソビ)-群青.mflac

文件地址: 
https://www.gobacklinus.tk/index.php/s/E3N6eQFHJqR6GCP/download
