### ISSUE TITLE
对 Wiki 和浏览器扩展的建议

### ISSUE THREAD

**Issue by lc6464** [unlock-music/unlock-music#170]
1. Wiki
    - 建议把使用提示页面的 Microsoft Edge 的下载地址改为 [https://www.microsoft.com/zh-cn/edge](https://www.microsoft.com/zh-cn/edge)，这是正式版的。
    - Home Page 可以加点东西
2. 浏览器扩展的更新也要跟上吧？

> ![Wiki 截图](https://user-images.githubusercontent.com/64722907/126022971-576e1762-a9cb-44b8-935d-fecab76681a5.png)
> Wiki 使用提示 截图

> ![Wiki 截图](https://user-images.githubusercontent.com/64722907/126022983-b672cf0e-f307-4ed4-9921-dec497b1b0dc.png)
> Wiki Home Page 截图

> ![Edge 外接程序网站截图](https://user-images.githubusercontent.com/64722907/126023008-21b50b79-a0ae-49de-a56b-0349ea5bca82.png)
> Edge 外接程序网站 截图

**Comment by ix64** [comment]
感谢所提建议。Wiki已更新。
扩展程序方面，目前更新策略是跟随GitHub Release更新，Pre-release 部分不发布更新。
因为上传相关商店需要人工操作，审核周期漫长，且需要较多的沟通工作。
