### ISSUE TITLE
批量处理好多kgm音乐，有几个报错的，但是浏览器里错误信息很快就没了，也不知道是哪几个文件，能否改善一下？

### ISSUE THREAD

**Issue by jhtnba** [unlock-music/unlock-music#174]
批量处理好多kgm音乐，有几个报错的，但是浏览器里错误信息很快就没了，也不知道是哪几个文件，能否改善一下？，或者增加个报错信息文件名单，非常感谢

**Comment by ix64** [comment]
可以按`F12`打开Console, 其中会显示所有错误消息
