### ISSUE TITLE
npm run serve本地调试时，kgm转换正常；但是build后，部署在线上，转换失败

### ISSUE THREAD

**Issue by sunhao0313** [unlock-music/unlock-music#175]
**Bug描述**

npm run serve本地调试时，kgm转换正常；但是build后，部署在线上，转换出的mp3无法播放

**复现方法**

1、git clone 最新代码 ，分支为master
2、npm i && npm run build
3、部署（通过nginx）
4、选择一个kgm，转换的文件可以下载，点击播放，无法播放，如下图
![image](https://user-images.githubusercontent.com/46696714/128227534-063bf34c-ba27-4ae4-8e2a-15835d771cbc.png)

但是，同样的代码 npm run serve 本地调试的时候，执行步骤4，转换成功，可以播放，如下图
![image](https://user-images.githubusercontent.com/46696714/128227791-97460643-84cf-456d-bd19-47bf404c0313.png)

**程序截图或者Console报错信息**

无报错console信息打印

**环境信息:**

 - 操作系统和浏览器： MacOS 11.3.1 (20E241)  / 谷歌浏览器
 - 程序版本：最新代码构建
 - 获取音乐文件所使用的客户端及其版本信息：酷狗音乐(mac) 版本2.9.5 (1104)

**附加信息**
打印了一下blob，还是有明显区别的
可以播放的
![image](https://user-images.githubusercontent.com/46696714/128228332-abe8d036-a680-47b4-a3b6-7c783dc024fb.png)

不可以播放的
![image](https://user-images.githubusercontent.com/46696714/128228447-cceefa67-ba57-488a-bbea-1b49606b408d.png)

**Comment by sunhao0313** [comment]
找到原因了，可以关闭咯

**Comment by sunhao0313** [comment]
在kgm.ts 中 ，fetch('./static/kgm.mask') 为啥在build之后，network中对其的请求url变成了  http://domain/js/static/kgm.mask导致了资源404，所以无法解码

**Comment by ix64** [comment]
感谢。此问题在 #177 以及 6737e8c1 应该已经解决，并包含与 v1.9.0 的更新中
