### ISSUE TITLE
解密qmcogg文件时报错：TypeError: e.readUInt8 is not a function

### ISSUE THREAD

**Issue by qmr0234** [unlock-music/unlock-music#179]
* 请按照此模板填写，否则可能立即被关闭

- [x] 我确认已经搜索过Issue不存并确认相同的Issue

**Bug描述:**

使用v1.9.0版音乐解锁解密qmcogg文件时报错：
TypeError: e.readUInt8 is not a function，孙燕姿 - 任性 (录音室Demo版).qmcogg，参考使用提示
同一文件使用v1.8.1版本的音乐解锁可以正常解密。

**复现方法**

[孙燕姿 - 任性 (录音室Demo版).zip](https://github.com/unlock-music/unlock-music/files/7019563/-.Demo.zip)

**环境信息:**

 - 操作系统和浏览器：Microsoft Edge 版本 92.0.902.73
 - 程序版本：v1.9.0
 - 获取音乐文件所使用的客户端及其版本信息：QQ音乐 17.14

**附加信息**

其他能够帮助确认问题的信息

**Comment by hongwen000** [comment]
同样遇到这个问题，1.81版本可用

**Comment by ix64** [comment]
已查明情况，是由于 Borewit/music-metadata 依赖库代码有问题，导致ogg文件解锁后读取信息阶段失败
