### ISSUE TITLE
“出现问题：mgg格式仅提供实验性支持”

### ISSUE THREAD

**Issue by Qlub53** [unlock-music/unlock-music#182]
* 请按照此模板填写，否则可能立即被关闭

- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [x] 我有证据表明这是程序导致的问题（如不确认，可以在[Discussions](https://github.com/ix64/unlock-music/discussions)内提出）

**Bug描述**

拖拽.mgg文件至html页面指定区域，页面右上角随即谈窗报错“出现问题：mgg格式仅提供实验性支持”

**复现方法**

拖拽.mgg文件至html页面指定区域
[demo.mgg.zip](https://github.com/unlock-music/unlock-music/files/7116282/demo.mgg.zip)

**程序截图或者Console报错信息**
![Screen Shot 2021-09-06](https://user-images.githubusercontent.com/1547593/132225072-dff783cd-dcf0-480b-87d4-05114b0be96b.png)

**环境信息:**

 - 操作系统和浏览器：macOS Catalina 10.15.7; Chrome 92.0.4515.159 (Official Build) (x86_64)
 - 程序版本：Build 2021/08/27 lagacy.zip
 - 获取音乐文件所使用的客户端及其版本信息：QQ音乐 for Mac v7.7.5.2

**附加信息**

其他能够帮助确认问题的信息

**Comment by Qlub53** [comment]
@ix64   ????
直接close了？

**Comment by ix64** [comment]
Duplicate of #51
