### ISSUE TITLE
新增转换时封面图片最长边不超过500px的选项

### ISSUE THREAD

**Issue by linancn** [unlock-music/unlock-music#183]
- 请按照此模板填写，否则可能立即被关闭

**背景和说明**

目前大多数汽车车机系统以及老设备播放FLAC或MP3时，封面能够正确显示出来，要求图片尺寸的最长边不能超过500px。

如果加一个这样的导出选项，能直接解决很多设备播放时封面不显示的问题。用户不再需要二次处理。

**实现途径**

- 对于超过500*500px的封面，找到图片的最长边，将其缩小为500px，另一边按比例缩放。

**附加信息**

更多你想要表达的内容

**Comment by ix64** [comment]
网易云和QQ音乐自动添加图片的，很久之前就添加了500x500的限制了啊？你有具体的错误样例吗？
