### ISSUE TITLE
旧版v1.7.1可以成功解锁《銀の龍の背に乗って_中島みゆき_恋文.mflac》，而最新版v1.9.1解锁失败。

### ISSUE THREAD

**Issue by leftcausedit** [unlock-music/unlock-music#185]
* 请按照此模板填写，否则可能立即被关闭

- [y] 我确认已经搜索过Issue不存并确认相同的Issue
- [y] 我有证据表明这是程序导致的问题（如不确认，可以在[Discussions](https://github.com/ix64/unlock-music/discussions)内提出）

**Bug描述**
旧版v1.7.1可以成功解锁《銀の龍の背に乗って_中島みゆき_恋文.mflac》，而最新版v1.9.1解锁失败。

**复现方法**

描述复现方法，必要时请提供样本文件
[银の龙の背に乗って](https://github.com/leftcausedit/public/releases/download/music/song.mflac)

**程序截图或者Console报错信息**
![image](https://user-images.githubusercontent.com/61641382/135727751-e0b6e207-6a84-43fb-921f-20270af03d24.png)

![image](https://user-images.githubusercontent.com/61641382/135727768-1a089002-b8c5-4b68-b635-5fbf04cc6fc3.png)

如果可以请提供二者之一

**环境信息:**

 - 操作系统和浏览器：win10 21H1 edge
 - 程序版本：
 - 获取音乐文件所使用的客户端及其版本信息：qqmusic最新版v18.22

**附加信息**

其他能够帮助确认问题的信息

**Comment by youqingkui** [comment]
文件超过大小？

**Comment by microka** [comment]
和楼主同样的情况，[Sample](https://github.com/microka/temp/releases/download/1.0/BD7DB4F718185992FA29180348C022CE.mflac) 用 1.9.1 无法解锁，用 1.7.1 和 1.7.2 则可正常解锁。

**Comment by ix64** [comment]
[v1.10.0-beta.1](https://github.com/unlock-music/unlock-music/releases/tag/v1.10.0-beta.1) 已解决此问题
