### ISSUE TITLE
新功能建议：对解密失败的音乐文件进行列表，而不仅是 toast 提示。

### ISSUE THREAD

**Issue by ENDsoft233** [unlock-music/unlock-music#188]
- 请按照此模板填写，否则可能立即被关闭

**背景和说明**

我经常对在 QQ 音乐中下载的加密音乐文件进行批量解密，但并不使用文档中提供的旧版本 PC QQ 音乐。

于是我经常遇到一些无法解密的音乐，对此我可能要对其进行再处理（比如单曲购买），但是 toast 弹窗时间短，统计难，提示信息指向性不高，所以我需要额外花时间去比对解密成功的文件与原来提供的文件有哪些异同，这很令我烦恼。

**实现途径**

对此，我想要求实现一个失败列表，列出原始文件名及失败的原因。

**附加信息**

无

**Comment by Akarinnnnn** [comment]
要不先写到一个txt凑合着用

**Comment by ENDsoft233** [comment]
注意到在控制台已经有相关输出，问题解决。
