### ISSUE TITLE
批量解锁音乐在下载的时候会漏掉部分音乐

### ISSUE THREAD

**Issue by Phishion** [unlock-music/unlock-music#189]
* 请按照此模板填写，否则可能立即被关闭

- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [x] 我有证据表明这是程序导致的问题（如不确认，可以在[Discussions](https://github.com/ix64/unlock-music/discussions)内提出）

**Bug描述**

比如我有 15 个音乐，批量拖进解锁框里面，解锁完成点击“下载全部”的时候，可能只下载 13 个音乐出来，这个时候重新拖进那 2 个没有下载的，解锁和再次下载又正常了，或者单独在下面的 Item 点击下载图标也可以正常下载。

漏下载的文件不固定，漏下载的文件数量亦不固定

**复现方法**

大概 15 个 ncm 文件，无论是勾选立即保存，还是选择在解锁完之后统一下载，都会触发这个 bug.

**程序截图或者Console报错信息**

程序无报错

**环境信息:**

 - 操作系统和浏览器：Big Sur 11.2.3 / Safari 14.0.3
 - 程序版本：v1.9.1
 - 获取音乐文件所使用的客户端及其版本信息：网易云 mac 版本 2.3.5

**附加信息**
样本：https://music.163.com/album?id=507804，解码格式为 ncm -> flac
这个 bug 很容易就复现，跟解码应该没有关系，感觉就是没有跟 Safari 提交下载请求

**Comment by ix64** [comment]
这个难以解决，所有下载请求都是按顺序逐个遍历发送给浏览器的。可能是浏览器限制。
文件较多的情况下，建议勾选自动保存，直接存入硬盘而不是调用下载。
![image](https://user-images.githubusercontent.com/13902388/146298089-008e2fb7-fbe4-4201-aa1b-35b916047cbc.png)
