### ISSUE TITLE
对于QQ音乐安卓客户端mgg1格式的支持

### ISSUE THREAD

**Issue by xhacker-zzz** [unlock-music/unlock-music#193]
**背景和说明**

QQ音乐安卓客户端出现新加密格式mgg1

**实现途径**

- 通过对新版本apk涉及播放的部分进行逆向工程和查看mgg1的16进制编码解析解密方法

**附加信息**

mgg1目前无法通过修改后缀名解密
[新版apk](https://share.weiyun.com/ozVs9L7p) 
[mgg1样本](https://share.weiyun.com/FPFp9684)

**Comment by gyl2565309278** [comment]
而且点击下载的时候，HQ高品质的歌曲全变成了4-6MB，而不是9-12MB，下载完以后查看信息发现编码率是192，而不是320。。这应该怎么解决呀

**Comment by zyybjd** [comment]
什么时候才可以支持mflac格式的破解，我希望新增一下这个的完美破解，但我又不知道该怎么说难受

**Comment by rekcah1986** [comment]
是mggl吧？

**Comment by xc1984759471** [comment]
![截图_2021-11-16_15-50-08](https://user-images.githubusercontent.com/53083866/141944434-8039ff2d-aa6b-457f-afdc-7dd7a308f456.png)
我还发现有一种无文件格式后缀的文件，不确定是什么格式，后面完全没有后缀，但是通过文件名可以判断出那个应该也是加密格式

**Comment by zyybjd** [comment]
我是苹果用户，我这边格式显示的是mflac

**Comment by ix64** [comment]
[v1.10.0-beta.1](https://github.com/unlock-music/unlock-music/releases/tag/v1.10.0-beta.1) 已解决此问题

**Comment by JeffersonGoodall** [comment]
> 

小白的我该怎么用这个测试版的啊？

**Comment by JeffersonGoodall** [comment]
> [v1.10.0-beta.1](https://github.com/unlock-music/unlock-music/releases/tag/v1.10.0-beta.1) 已解决此问题

小白的我该怎么用这个测试版的啊？
