### ISSUE TITLE
建议经快更新破解QQ音乐mflac格式功能

### ISSUE THREAD

**Issue by zyybjd** [unlock-music/unlock-music#194]
**我下载歌曲一般都在QQ音乐上**

我发现国内主流音乐软件中QQ音乐的音质和资源普遍比网易云音乐要好，所以下载歌曲一般都在QQ音乐上

**建议可以主攻一下后面的缺点**

我觉得可以考虑多破解一下，因为QQ音乐主流格式变成了mflac.

**Comment by i-iooi-i** [comment]
的确如此 最近发现下载下来的音乐格式不少都变成这个格式了，无法破解出来了。
