### ISSUE TITLE
QQ 音乐 新格式mflac0

### ISSUE THREAD

**Issue by haiyan1301** [unlock-music/unlock-music#198]
更改后缀没用

**Comment by Zhangxiaolong-killer** [comment]
确实，希望增加对mflac0格式的支持

**Comment by hugejile** [comment]
这个格式pc的qqmusic也不支持

**Comment by ix64** [comment]
[v1.10.0-beta.1](https://github.com/unlock-music/unlock-music/releases/tag/v1.10.0-beta.1) 已解决此问题
