### ISSUE TITLE
Error: gg audio-codec not recognized (id=v r"is)，lwfi-Falling for You.mgg，

### ISSUE THREAD

**Issue by Ineocode** [unlock-music/unlock-music#203]
* 请按照此模板填写，否则可能立即被关闭

- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [x] 我有证据表明这是程序导致的问题（如不确认，可以在[Discussions](https://github.com/ix64/unlock-music/discussions)内提出）

**Bug描述**

mac 系统下载的QQ音乐mgg格式解锁失败

**复现方法**

复现文件：lwfi-Falling for You.mgg

**程序截图或者Console报错信息**

Error: gg audio-codec not recognized (id=v r"is)，lwfi-Falling for You.mgg，

**环境信息:**

 - 操作系统和浏览器：mac Big sur 11.5.2        chrome 版本 96.0.4664.55
 - 程序版本：v1.9.1
 - 获取音乐文件所使用的客户端及其版本信息：QQ 音乐版本 7.9.1 bulid 00

**附加信息**

其他能够帮助确认问题的信息

**Comment by ix64** [comment]
[v1.10.0-beta.1](https://github.com/unlock-music/unlock-music/releases/tag/v1.10.0-beta.1) 已解决此问题
