### ISSUE TITLE
CI 在发布 jest coverage 时出错

### ISSUE THREAD

**Issue by jixunmoe** [unlock-music/unlock-music#217]
todo

- [ ] 能够正常 publish jest coverage
- [ ] 合并到其他分支

**Comment by ix64** [comment]
确实，是上游的一个bug，稍后尝试修复一下

**Comment by ix64** [comment]
fixed with https://github.com/unlock-music/unlock-music/commit/058985de4f003e2fbdfc4261e2d172c1f9c1c4db
