### ISSUE TITLE
MOO音乐新格式(.bkcm4a)

### ISSUE THREAD

**Issue by nr0728** [unlock-music/unlock-music#222]
**说明**

Moo音乐新格式bkcm4a

**附加信息**

如果没有此种文件，请回复我

**Comment by ix64** [comment]
OK
看了下源代码，总共有 `".bkc" + {"mp3", "m4a", "flac", "wav", "ape", "ogg", "wma"}` 这么多种

**Comment by nr0728** [comment]
.bkcm4a源文件
https://pan.baidu.com/s/14I72WJ-22UpXOXVvzti7-Q
提取码:pfxa
