### ISSUE TITLE
File Size Too Large

### ISSUE THREAD

**Issue by Justinwang677** [unlock-music/unlock-music#228]
Sorry, my Chinese isn't that good yet. But was wondering if you could increase the file size for unlocking songs. Kugou VIP downloads can reach up to 300 MB and every time I try unlocking a song over 80 MB, it tells me the file is too large. Is it possible to remove the file size restriction all together?

**Comment by ix64** [comment]
This limit is caused by the size of `public/static/kgm.mask` (4MB). So it can only decrypt ~64MB files.
You can download and use https://github.com/unlock-music/cli to avoid this restriction.
If we found a better decrypt algorithm, this restrict will remove on web version too.
