### ISSUE TITLE
对于QQ音乐 Hires的解锁频率 被削弱至20KHZ

### ISSUE THREAD

**Issue by j1ans** [unlock-music/unlock-music#239]
(https://imgur.com/a/5EEPgwj)
此为unlock-music项目解锁的Hires音频 可以看到在20KHZ的部分几乎一刀切了
![BO8DEB7%PAYWAT2@Y`13V16](https://user-images.githubusercontent.com/40492732/149633008-7c18c829-029c-40aa-967a-037c34a23bac.png)
此为QQ音乐原生的Hires音乐 可以看到SACD特有的高频噪音

希望开发者可以改进对于Hires的解锁算法

**Comment by ix64** [comment]
音质问题与本项目 **没有任何关系**，本项目按照加密前的 **原样** 将文件解密给你。因此，有任何问题音质请联系 **QQ音乐**。
