### ISSUE TITLE
`.mflac` 可能是包含Key的 Flac

### ISSUE THREAD

**Issue by lunjielee** [unlock-music/unlock-music#240]
* 请按照此模板填写，否则可能立即被关闭

- [ ] 我确认已经搜索过Issue不存并确认相同的Issue
Duplicate of #169 
- [x] 我有证据表明这是程序导致的问题（如不确认，可以在[Discussions](https://github.com/ix64/unlock-music/discussions)内提出）

**Bug描述**

Error: FourCC contains invalid characters: 12 7e 11 09 "~ "，YOASOBI (ヨアソビ)-群青.mflac

**复现方法**

[样本文件](https://www.gobacklinus.tk/index.php/s/E3N6eQFHJqR6GCP/download)

**程序截图或者Console报错信息**

如果可以请提供二者之一

**环境信息:**

 - 操作系统和浏览器：macOS 10.17 Chrome97
 - 程序版本：v1.10.0-c48dbd8
 - 获取音乐文件所使用的客户端及其版本信息：QQ音乐 8.0.0.3

**附加信息**

其他能够帮助确认问题的信息

**Comment by ix64** [comment]
你好，此文件为未加密的FLAC，可以直接改后缀名为 `.flac`。
我们将尝试复现这一结果，以确认需要自动进行检测并处理此种情况

**Comment by lunjielee** [comment]
> 你好，此文件为未加密的FLAC，可以直接改后缀名为 `.flac`。 我们将尝试复现这一结果，以确认需要自动进行检测并处理此种情况

删除文件重新下载后通过file查看文件类型为data而不是flac，并且能够正常解锁，可能是qq音乐出bug了导致第一次下载的时候没有加密吧

**Comment by ix64** [comment]
我们也没法复现此情况，如果有任何发现，可以 Re-Open 此 Issue。
