### ISSUE TITLE
酷狗发来dmca通知

### ISSUE THREAD

**Issue by Akarinnnnn** [unlock-music/unlock-music#242]

**Comment by isfk** [comment]
大家赶紧吧，别等删了

**Comment by ix64** [comment]
已处理
https://github.com/unlock-music/unlock-music/commit/6bfaed129e3c7a38f377037e1056eb12396e383b
https://github.com/unlock-music/unlock-music/commit/18656e22f74abaa18200e22e804cd1bc947209f8

已回复 GitHub Trust & Safety
> Hello GitHub Trust & Safety:
>    
>  Receiving the DMCA notice you sent us, we have removed all content related to "Kugou", as requested accordingly.
>  We have remove `src/decrypt/kgm.ts` and `public/static/kgm.mask` from all the git history.
>  
>  Thanks,
>  MengYX

**Comment by cxw620** [comment]
如果QQ音乐也发来DMCA就彻底无了，真的糟糕（难道真的要普及声卡内录的方法了？）
