### ISSUE TITLE
QQ音乐发来DMCA通知

### ISSUE THREAD

**Issue by lvzx123** [unlock-music/unlock-music#256]
https://github.zendesk.com/attachments/token/V4ZD2xCrY56sv6cLtmbQuzBtk/?name=2022-02-23-qqmusic.rtf/attachments/token/V4ZD2xCrY56sv6cLtmbQuzBtk/?name=2022-02-23-qqmusic.rtf

**Comment by Akarinnnnn** [comment]
小作文，需要自取

Hello GitHub Trust & Safety:

Receiving the DMCA notice you sent us, we have removed all content related to "QQ Music" and “MOO”, as requested accordingly.
We have remove src/decrypt/kgm.ts and public/static/kgm.mask from all the git history.

Thanks,
MengYX
