### ISSUE TITLE
无法清除音乐解锁

### ISSUE THREAD

**Issue by zhouppppp** [unlock-music/unlock-music#257]
* 请按照此模板填写，否则可能立即被关闭

- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [x] 我有证据表明这是程序导致的问题（如不确认，可以在[Discussions](https://github.com/ix64/unlock-music/discussions)内提出）

**Bug描述**
用v2ray八合一版本伪装的音乐解锁无法清除
简要地复述你遇到的Bug
用v2ray八合一版本伪装的音乐解锁无法清除，重装系统，解除DNS，都无法清除音乐解锁，相当于IP被锁定成了音乐解锁的页面
**复现方法**

描述复现方法，必要时请提供样本文件

**程序截图或者Console报错信息**

如果可以请提供二者之一

**环境信息:**

 - 操作系统和浏览器：
 - 程序版本：
 - 获取音乐文件所使用的客户端及其版本信息：

**附加信息**

其他能够帮助确认问题的信息

**Comment by ix64** [comment]
应该是由于 pwa 造成的，可以unregister servicer worker
