### ISSUE TITLE
[bug]解锁文件名乱码

### ISSUE THREAD

**Issue by AKlutz** [unlock-music/unlock-music#263]
如题 正常文件名 解锁之后 名称会乱码
![1](https://user-images.githubusercontent.com/38929049/157195505-cfca42a2-c703-4762-91e7-255ec338bae7.png)
![2](https://user-images.githubusercontent.com/38929049/157195507-a875c6b0-cfba-409f-a612-fa4902fd264f.png)

**Comment by AKlutz** [comment]
部分文件会出现这种情况

**Comment by ix64** [comment]
似乎是 GBK编码 的问题，此类问题是由于制作音频的软件不遵循ID3规范导致；
程序无法自动检测，因此我们不会处理
