### ISSUE TITLE
为什么安装完后是请勿直接运行此代码

### ISSUE THREAD

**Issue by muhanxiaobai** [unlock-music/unlock-music#269]
安装完后是请勿直接运行此代码

**Comment by cyleonebk** [comment]
应该是要通过浏览器访问

**Comment by ix64** [comment]
请阅读 README 的使用方法，源代码需要构建后运行

**Comment by muhanxiaobai** [comment]
我已经自己搞好了感谢



***@***.***
 
发件人： MengYX
发送时间： 2022-04-09 17:22
收件人： unlock-music/unlock-music
抄送： muhanxiaobai; Author
主题： Re: [unlock-music/unlock-music] 为什么安装完后是请勿直接运行此代码 (Issue #269)
请阅读 README 的使用方法，源代码需要构建后运行
