### ISSUE TITLE
部分 kgm(a) 文件无法解密

### ISSUE THREAD

**Issue by g-mph** [unlock-music/unlock-music#271]
例如：

>出现问题
>Error: Not a valid kgm(a) file!，Lenka - The Show.kgma，参考[使用提示](https://github.com/ix64/unlock-music/wiki/%E4%BD%BF%E7%94%A8%E6%8F%90%E7%A4%BA)

**Comment by g-mph** [comment]
之前 `欢迎使用IXarea 酷狗音乐Kgm/Vpr解锁工具 Alpha-2 Build 2020/04/17` 的都可以正常解锁这些。

**Comment by ix64** [comment]
请提供样例

**Comment by g-mph** [comment]
样例：<https://wetransfer.com/downloads/af6761d82dd26f23fb33c5220f72aa9a20220409123916/b024cfd58f26aa765482bb10df9ed19720220409123916/4f6586>

另外 CLI 程序提示：`conversion failed       {"source": "Lenka - The Show.kgma"}`

**Comment by ix64** [comment]
你好，此文件是 **未加密的** FLAC，直接修改后缀名即可；我们后续将添加此项检查
