### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by canon9826** [unlock-music/unlock-music#273]
兄弟，感谢你开发这个用来解码的软件，但是，我今天使用1.10版本进行解码mflac文件的时候，将200多个文件拉入选择框，然后开始解码，cpu和内存开始不正常的占用（我的cpu是i5--7300,内存有16G），解锁两三个文件后，直接内存占满，并且浏览器直接崩溃，我这边也不知道你的程序中有没有日志这一说，但是页面控制台的报错我可以提供给你
![image](https://user-images.githubusercontent.com/46148177/161811892-ec759306-89c8-4e33-9b9b-fc1879e823dd.png)
![image](https://user-images.githubusercontent.com/46148177/161812324-6289b898-6259-414f-892f-1c4978683b88.png)
![image](https://user-images.githubusercontent.com/46148177/161812325-638c0b28-92dc-4d19-91da-804cb6e80a84.png)

**Comment by ix64** [comment]
你好，大批量解锁请使用CLI程序 https://github.com/unlock-music/cli
