### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 495129576** [unlock-music/unlock-music#274]
Error: FourCC contains invalid characters: d0 4d 8e ff "ÐMÿ"，侧田 - 感动 [mqms2].mflac0，参考[使用提示](https://github.com/ix64/unlock-music/wiki/%E4%BD%BF%E7%94%A8%E6%8F%90%E7%A4%BA)

**Comment by 495129576** [comment]
I just try again,doesn't work

**Comment by ix64** [comment]
Duplicate of #267
QMCv3 is not supported for now.
