### ISSUE TITLE
部分qmcogg文件解锁失败

### ISSUE THREAD

**Issue by Fu-Inaru** [unlock-music/unlock-music#296]
最新版本QQ音乐下载得来的qmcogg、mgg等类型文件大面积出现解锁失败的现象；即使使用旧版本QQ音乐可以解决部分文件的问题，但仍存在部分文件**虽然显示“解锁成功”而解锁后却只能得到一个无法打开的ogg文件**。另外，目前的Android端QQ音乐的mgg1文件也会出现此类现象。以下为几个实例：
[Sample1.zip](https://github.com/unlock-music/unlock-music/files/9250381/Sample1.zip)
[Sample2.zip](https://github.com/unlock-music/unlock-music/files/9250388/Sample2.zip)
[Sample3.zip](https://github.com/unlock-music/unlock-music/files/9250390/Sample3.zip)

作为对比，此处给出一个新版QQ音乐无法解决而旧版可以的文件的例子：
[Sample4.zip](https://github.com/unlock-music/unlock-music/files/9250393/Sample4.zip)
谢谢。

**Comment by cxw620** [comment]
新版客户端改加密方式了, 似乎没有办法离线解密

**Comment by shen020598** [comment]
不是吧？云端加密吗？不会那么狠吧？？

**Comment by Ryanjiang2009** [comment]
我是录屏的

**Comment by jixunmoe** [comment]
前三个文件未加密，后缀名改为 ogg 可以直接使用浏览器播放。

第四个文件可以正常解密。

**Comment by Fu-Inaru** [comment]
> 前三个文件未加密，后缀名改为 ogg 可以直接使用浏览器播放。
> 
> 第四个文件可以正常解密。

哦！原来如此！我就说旧版客户端怎么可能有新鲜的加密方式……
十分感谢！
