### ISSUE TITLE
[QQ音乐] 支持Windows客户端1763以上使用512 Bytes Key加密的mgg/mflac文件

### ISSUE THREAD

**Issue by kmzs123** [unlock-music/unlock-music#51]
旧版的QQ音乐下载的qmcflac可以解锁，更新后下载的mflac就不能解锁了

文件下载链接：
[QQ音乐的链接](https://c.y.qq.com/base/fcgi-bin/u?__=I4O6I)
[新版mflac](https://dl.kmzs123.cn/unlock-music/%E9%AB%98%E6%A2%A8%E5%BA%B7%E6%B2%BB%20(%E3%81%9F%E3%81%8B%E3%81%AA%E3%81%97%20%E3%82%84%E3%81%99%E3%81%AF%E3%82%8B)%20-%20FAIRY%20TAIL%20%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%86%E3%83%BC%E3%83%9E.mflac) （已失效）
[旧版qmcflac](https://dl.kmzs123.cn/unlock-music/%E9%AB%98%E6%A2%A8%E5%BA%B7%E6%B2%BB%20(%E3%81%9F%E3%81%8B%E3%81%AA%E3%81%97%20%E3%82%84%E3%81%99%E3%81%AF%E3%82%8B)%20-%20FAIRY%20TAIL%20%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%86%E3%83%BC%E3%83%9E.qmcflac) （已失效）

**Comment by ix64** [comment]
你好，经确认，这应该不是我们目前常见的mflac格式。
目前常见的mflac格式使用256bytes的密钥，当前的算法基本能够进行解密。
但你提供的mflac文件使用的是512bytes的密钥。
请问你使用的操作系统、客户端版本分别是什么？

**Comment by kmzs123** [comment]
win10 1909 
QQ音乐 1763
unlock-music 1.5.1
基本上就是全是最新的

**Comment by kmzs123** [comment]
> 你好，经确认，这应该不是我们目前常见的mflac格式。
> 目前常见的mflac格式使用256字节的密钥，当前的算法基本能够进行解密。
> 但你提供的mflac文件使用的是512字节的密钥。
> 请问你使用的操作系统，客户端版本分别是什么？

win10 1909
QQ音乐 1763
unlock-music 1.5.1
基本上就是全是最新的稳定版

**Comment by ix64** [comment]
成功复现，但仅这首歌获取到512Byte的加密版本，其他歌曲仍在使用256Byte的密钥。
因此在发现更多歌曲开始使用新的加密方案之前，将暂不准备进行适配。

**Comment by Zhanglv0413** [comment]
win10 1909
QQ音乐 3.11.0
以下几首歌曲无法成功解码，由于是vip所以直接提供文件
链接：https://pan.baidu.com/s/1gppJbS2ODC1c4n0bQSrZqQ 
提取码：a4hb

**Comment by ix64** [comment]
由 @Zhanglv0413 提供的信息

> win10 1909 QQ音乐 3.11.0
> 以下几首歌曲无法成功解码，由于是vip所以直接提供文件
> 链接：https://pan.baidu.com/s/1gppJbS2ODC1c4n0bQSrZqQ
> 提取码：a4hb

**Comment by 17huiwei** [comment]
QQ 17.66.0.0，搜索 Michael Buble - Have Yourself a Merry Little Christmas 这首歌曲也不行。

**Comment by machi9527** [comment]
MGG格式可以解锁 在页面可以听 但是下载后就变成OGG了

**Comment by ix64** [comment]
> MGG格式可以解锁 在页面可以听 但是下载后就变成OGG了

Mgg解锁后格式一般为Ogg。Ogg与Mp3类似，是一种开放的格式
另，你的问题与词Issue无关，将Hide

**Comment by Fwagan** [comment]
无法解锁的文件样本
链接: https://pan.baidu.com/s/1ZKdcVCz4uOzwFGbVRWJcFw
提取码: 5ip7

**Comment by 17huiwei** [comment]
现在这个问题有没有解决呢？

**Comment by ix64** [comment]
近期其他事情比较忙，没有开始处理此问题


--------------原始邮件--------------
发件人："17huiwei "<notifications@github.com&gt;;
发送时间：2020年7月4日(星期六) 上午9:25
收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;;
抄送："MengYX "<admin@mengyx.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [ix64/unlock-music] [QQ音乐] 支持Windows客户端1763以上使用512 Bytes Key加密的mgg/mflac文件 (#51)
-----------------------------------

 

 
现在这个问题有没有解决呢？

**Comment by ix64** [comment]
预计1个星期后，我本人有时间继续进行这个项目。届时，将会优先处理此Issue。

**Comment by lttlcj** [comment]
https://pan.baidu.com/s/1QJ1_XsaUHn_LAQ53zxWF1Q
提取码：yvqo
QQ音乐版本17.77 无法使用MGG解密的样本

**Comment by ix64** [comment]
到目前暂未找到可行方案

**Comment by xermao** [comment]
> 到目前暂未找到可行方案
 算法变了吗？

**Comment by xermao** [comment]
> 到目前暂未找到可行方案

是算法变了吗？

**Comment by bqw5354** [comment]
这首老歌也报错“mflac格式仅提供实验性支持”，是同样的512Byte的问题吗？
![mflac](https://user-images.githubusercontent.com/62192764/98049060-f7208600-1dfc-11eb-80f1-164b3e019c36.JPG)

**Comment by lc6464** [comment]
- Windows 10 企业版 20H2 `19042.662` `Windows Feature Experience Pack 120.2212.1070.0`
- QQ音乐 `17.66.5297.0508`
- `.mflac` 文件

出现进度条不会动的情况。
旧版QQ音乐（好像是几年之前的版本了）下载 `.mflac` 文件可以正常解锁，新版不行。
文件无法上传（文件过大，GitHub 只允许小于10MB的文件），无论是新版下载的还是旧版下载解锁后的都不行。

**Comment by xermao** [comment]
QQ音乐自身是如何解密的呢，如果是因为有密钥问题，可以直接从QQ音乐程序内存里获取KEY来解密吗

**Comment by lc6464** [comment]
> QQ音乐自身是如何解密的呢，如果是因为有密钥问题，可以直接从QQ音乐程序内存里获取KEY来解密吗

这恐怕只有QQ音乐的开发团队清楚了，或者使用一些~~技术手段~~了。

**Comment by ix64** [comment]
@lc6464 进度条不动的问题，可以邮件提供一下样本文件吗

**Comment by ix64** [comment]
> QQ音乐自身是如何解密的呢，如果是因为有密钥问题，可以直接从QQ音乐程序内存里获取KEY来解密吗

因为目前512Bytes Key的mflac只在Windows客户端出现（其实512Bytes Key的文件Key->Mask的算法也发生了变化），Windows客户端他们用的纯C++写，比较难搞。等什么时候Android也上mflac再看看吧

**Comment by lc6464** [comment]
> @lc6464 进度条不动的问题，可以邮件提供一下样本文件吗

依然是附件过大，我使用了另一项服务暂存了文件，有效期24h，单个链接可下载次数10次。
取件密码均为 `github@mix64.cn`。

- **新版**QQ音乐下载的**无法正常转换**的 `.mflac` 文件地址：[https://airportal.cn/87797](https://airportal.cn/87797)
- **旧版**QQ音乐下载并**转换后**的 `.flac` 文件地址：[https://airportal.cn/61780](https://airportal.cn/61780)

**Comment by ix64** [comment]
@lc6464 在Windows10 Chrome, Edge, Firefox 进行测试，无法复现所述问题
![image](https://user-images.githubusercontent.com/13902388/101986787-0aabf000-3ccb-11eb-8cf9-33cfc0b5f570.png)

**Comment by lc6464** [comment]
> @lc6464 在Windows10 Chrome, Edge, Firefox 进行测试，无法复现所述问题
> ![image](https://user-images.githubusercontent.com/13902388/101986787-0aabf000-3ccb-11eb-8cf9-33cfc0b5f570.png)

我的用户代理：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.60

**Comment by lc6464** [comment]
@ix64 目前我自己也无法复现问题，可能是因为当时设备或者浏览器暂时出现了一点问题导致的，目前这种情况没有再现而是直接提示失败。
新版的 `.mflac` 文件可以确定无法正常转换。

**Comment by yinadd** [comment]
> [Https://pan.baidu.com/s/1QJ1_XsaUHn_LAQ53zxWF1Q](Https://pan.baidu.com/s/1QJ1_XsaUHn_LAQ53zxWF1Q)
> 提取码：yvqo
> Win10版本 1909 18363.959 QQ音乐版本17.77无法使用MGG解密的样本
> @ix64

mgg可以直接使用格式工厂转换成mp3

**Comment by lc6464** [comment]
> [Https://pan.baidu.com/s/1QJ1_XsaUHn_LAQ53zxWF1Q](Https://pan.baidu.com/s/1QJ1_XsaUHn_LAQ53zxWF1Q)
> 提取码：yvqo
> Win10版本 1909 18363.959 QQ音乐版本17.77无法使用MGG解密的样本
> @ix64

`.mgg` 是正常的音频格式，可以使用 `ffmpeg` 等软件转码为 `.mp3` `.flac` `.wav` 等格式，也可使用常见的播放器直接播放（如 `PotPlayer`），无需解锁。

**Comment by lc6464** [comment]
1. Windows 10 企业版 20H2 `19042.662` `Windows Feature Experience Pack 120.2212.1070.0`
2. Windows 10 企业版 20H2 **`19042.685`** `Windows Feature Experience Pack 120.2212.1070.0`
- QQ音乐 `17.66.5297.0508`
- `.mflac` 文件


同一个QQ音乐客户端（同一台电脑上的同一个客户端）下载的两个 `.mflac` 文件，一个可以解锁，另一个不可以。
出现问题的文件是在系统小更新之前（`19042.662`）下载的，歌曲是周杰伦的《青花瓷》，
正常解锁的文件是在系统小更新之后（**`19042.685`**）下载的，歌曲是周杰伦的《稻香》，
能否解锁和**系统**有关吗？

**Comment by ix64** [comment]
解锁本身与操作系统无关。

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："LC "<notifications@github.com&gt;;
发送时间：2021年1月6日(星期三) 上午8:21
收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;;
抄送："MengYX "<admin@mengyx.cn&gt;;"Mention "<mention@noreply.github.com&gt;;
主题：Re: [ix64/unlock-music] [QQ音乐] 支持Windows客户端1763以上使用512 Bytes Key加密的mgg/mflac文件 (#51)
-----------------------------------

 

  
Windows 10 企业版 20H2 19042.662 Windows Feature Experience Pack 120.2212.1070.0
 
Windows 10 企业版 20H2 19042.685 Windows Feature Experience Pack 120.2212.1070.0
   
QQ音乐 17.66.5297.0508
 
.mflac 文件
  
同一个QQ音乐客户端（同一台电脑上的同一个客户端）下载的两个 .mflac 文件，一个可以解锁，另一个不可以。
 出现问题的文件是在系统小更新之前（19042.662）下载的，歌曲是周杰伦的《青花瓷》，
 正常解锁的文件是在系统小更新之后（19042.685）下载的，歌曲是周杰伦的《稻香》，
 能否解锁和系统有关吗？

**Comment by zeroaq** [comment]
你好QQ音乐这首歌 The Cab - Lock Me Up 无法破解，mgg格式
![OR7D2}GP2412O(2R N)2)2](https://user-images.githubusercontent.com/42811972/104121784-da428a80-5338-11eb-93ed-8220016fb798.png)

**Comment by kasumiso8** [comment]
QQ音乐版本：17.91
.mflac格式 无法解锁
目前的新歌都无法破解，有好的办法吗？
样本链接：https://pan.baidu.com/s/1ahQ_JCZnFXLcx17x86kUNQ 
提取码：1234

**Comment by wc7086** [comment]
https://github.com/unlock-music/unlock-music/issues/145#issuecomment-824041224

**Comment by Sanluli36li** [comment]
18.22 无法解锁
https://36li.lanzoui.com/iQGzGt66vah

**Comment by CuteTony** [comment]
QQ音乐 Mac 7.7.5 build 02，来源MAS
已确认现在会些歌曲会使用新的mflac格式，无法解密
[样本链接(蓝奏云)](https://wwa.lanzoui.com/iDm0Mtdyoje)

**Comment by Akarinnnnn** [comment]
> QQ音乐 Mac 7.7.5 build 02，来源MAS，
> 已确认 Mac 端现在有些歌曲会使用新的 `.mflac` 以及 `.mgg` 格式，无法解密。建议使用旧版/暂缓更新。
> 
> 另外，比对无法解密的 `.mflac` 文件尾4字节，发现除了 #51 最初提到样本的 `C0 02 00 00` 之外，部分文件为 `0E 55 FF F0` 结尾，如图：
> <img alt="Screen Shot 2021-08-31 at 1 34 00 AM" width="526" src="https://user-images.githubusercontent.com/27068124/131381134-c7c0b6dc-9e41-48b2-827a-a685c4691030.png">
> 
> 附一个以此结尾的[样本链接(蓝奏云)](https://wwa.lanzoui.com/iDm0Mtdyoje)

以前`C0 02 00 00`是key的大小，现在这个可能连key本身都加密了

**Comment by ix64** [comment]
这是最近的研究进展 欢迎大家补充 https://gist.github.com/ix64/bcd72c151f21e1b050c9cc52d6ff27d5

**Comment by txwk** [comment]
> Mac 端旧版下载： https://mydown.yesky.com/macsoft/99931561/versions/ V7.6.5 应该是最后一个下载 qmcflac 的版本了

7.70应该是最后一个非mgg版本，我一直在用

**Comment by wc7086** [comment]
> 度盘太离谱了。

可以用阿里云盘

**Comment by jixunmoe** [comment]
> QQ音乐 Mac 7.7.5 build 02，来源MAS， 已确认 Mac 端现在有些歌曲会使用新的 `.mflac` 以及 `.mgg` 格式，无法解密。建议使用旧版/暂缓更新。
> 
> 另外，比对无法解密的 `.mflac` 文件尾4字节，发现除了 #51 最初提到样本的 `C0 02 00 00` 之外，部分文件为 `0E 55 FF F0` 结尾，如图： <img alt="Screen Shot 2021-08-31 at 1 34 00 AM" width="526" src="https://user-images.githubusercontent.com/27068124/131381134-c7c0b6dc-9e41-48b2-827a-a685c4691030.png">
> 
> 附一个以此结尾的[样本链接(蓝奏云)](https://wwa.lanzoui.com/iDm0Mtdyoje)

![image](https://user-images.githubusercontent.com/5713045/145739608-4d862ba2-57fa-4524-9f23-69ef94a430b0.png)

这个没有加密，直接改后缀名为 `flac` 就能播放。

**Comment by CuteTony** [comment]
To Whom It May Concern:This is an automatic reply, confirming that your E-mail was received.This E-mail (and any attachments or hyperlinks within it) will not be delivered until it passes the anti-virus check by TLAN Project.If you want to send files to me directly, simply click File Collect and follow the instructions.I offer my apology to you for the inconvenience has caused you.Best Regards.Tony  Guo

**Comment by CuteTony** [comment]
> > QQ音乐 Mac 7.7.5 build 02，来源MAS， 已确认 Mac 端现在有些歌曲会使用新的 `.mflac` 以及 `.mgg` 格式，无法解密。建议使用旧版/暂缓更新。
> > 另外，比对无法解密的 `.mflac` 文件尾4字节，发现除了 #51 最初提到样本的 `C0 02 00 00` 之外，部分文件为 `0E 55 FF F0` 结尾，如图： <img alt="Screen Shot 2021-08-31 at 1 34 00 AM" width="526" src="https://user-images.githubusercontent.com/27068124/131381134-c7c0b6dc-9e41-48b2-827a-a685c4691030.png">
> > 附一个以此结尾的[样本链接(蓝奏云)](https://wwa.lanzoui.com/iDm0Mtdyoje)
> 
> ![image](https://user-images.githubusercontent.com/5713045/145739608-4d862ba2-57fa-4524-9f23-69ef94a430b0.png)
> 
> 这个没有加密，直接改后缀名为 `flac` 就能播放。

看了下还真是，之前完全没想到看看文件头。
这就很迷惑了，难道腾讯还会混用改后缀的方式“加密”？还是说恰巧遇到了bug或者过渡时期的临时策略这类。这个样本确实是由QQ音乐Mac端下载来的。

**Comment by ix64** [comment]
[v1.10.0-beta.1](https://github.com/unlock-music/unlock-music/releases/tag/v1.10.0-beta.1) 已解决此问题
